### PR TITLE
Compatibility with Qt5

### PR DESCRIPTION
**Pull request by kazuki0824**
If you use a qt5-equipped distro (e.g. Ubuntu 18.04, Debian stretch), I don’t think it is really smart to newly install qt4 from apt only to satisfy dependency. This PR eliminates qt4 from all of the build scripts.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Review by LanderU — APPROVED** [review]
LGTM! We're fixing other things, when we finish with that issues we'll merge this. Thanks for your contribution.

**Comment by anasarrak** [comment]
@kazuki0824 There've been some changes on our fork, do you mind closing this and creating a new PR with the current ros branch?

**Comment by kazuki0824** [comment]
@anasarrak No, not at all. I’ll close it. Thanks.

**Comment by kazuki0824** [comment]
@anasarrak please close it after applying this PR.

**Comment by anasarrak** [comment]
Cherry picked the change to https://github.com/AcutronicRobotics/octomap/pull/6

**Pull request closed without merging**
